### ISSUE TITLE
PinePhone Compatibility

### ISSUE THREAD

**Issue by ghost** [flathub/io.mgba.mGBA#22]
I'm running Mobian (aarch64 based on Debian 11 with Phosh on wayland) on my PinePhone (3GB RAM model) with flatpak 1.8.3.

When I run mGBA, this is the error I get:
```Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, xcb.```

**Comment by CuriousTommy** [comment]
If I were to take a guess, it probably had to do with the following line:

https://github.com/flathub/io.mgba.mGBA/blob/ee446dd543f3f4f3fb34171f76ef42cb0e2cf164/io.mgba.mGBA.json#L14

If anyone else is running into this issue, I would try setting it to `--socket=fallback-x11` instead.
