### ISSUE TITLE
Controller setting disappeared after latest update (2023-10-30)

### ISSUE THREAD

**Issue by Tubo** [flathub/io.mgba.mGBA#41]
The controller settings disappeared after the latest commit, namely:
`9e749847a70a87987ab6e60e8958b601055b89422c2bc668fc23dfd4c8e169fd`.

I fixed by rolling back to
```
flatpak update --commit=67d710054e33d8afce979d0101385c5fbf69a9c36e6f38439cf080fe1afbe0d5 io.mgba.mGB
```

System:
Ubuntu 20.04 (KDE Neon)
KDE on Wayland

**Comment by Parnassius** [comment]
Fixed by #42, a new build will be available in a few hours at the latest
